name: ZUREZ
favicon: null
layout_spectrum: 0.25202
typography_spectrum: 0.4991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#ff0046'
    - '#ff85ff'
    - '#807e7f'
  brandStrength: 0.4375
  lightness: 0.5883951561991125
  saturation: 0.8484261739067733
  rhythmicContrast: 0.3279109743889421
purpose: []
